name: Myanmar Tools CI

on: [push]

jobs:

  # Training Data Project
  training-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          java-version: '8'
      - name: Training Data
        run: |
          cd training;
          mvn compile;
          mvn test
